### ISSUE TITLE
NullPointerException when RaygunClient.recordBreadcrumb() is called

### ISSUE THREAD

**Issue by AndriiVovkWorkspot** [MindscapeHQ/raygun4android#64]
2019-06-28 14:41:08.927 11019-11019/? W/System.err: java.lang.NullPointerException: Attempt to invoke interface method 'boolean java.util.List.add(java.lang.Object)' on a null object reference
2019-06-28 14:41:08.927 11019-11019/? W/System.err:     at com.raygun.raygun4android.CrashReporting.recordBreadcrumb(CrashReporting.java:65)
2019-06-28 14:41:08.927 11019-11019/? W/System.err:     at com.raygun.raygun4android.CrashReporting.recordBreadcrumb(CrashReporting.java:61)
2019-06-28 14:41:08.927 11019-11019/? W/System.err:     at com.raygun.raygun4android.RaygunClient.recordBreadcrumb(RaygunClient.java:216)

**Comment by TheRealAgentK** [comment]
Thx for reporting this, @AndriiVovkWorkspot - Which version of the provider are you using?

**Comment by AndriiVovkWorkspot** [comment]
4.0.0

**Comment by TheRealAgentK** [comment]
This is fixed for 4.0.1.
